# Generated by Django 6.0.3 on 2026-05-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polaris", "0014_auto_20220211_0624"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebAuthNonce",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("used", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
